theme: jekyll-theme-midnight
title: [Notes on software]
description: [Write notes here, so I do not forget.]



Enter text in [Markdown](http://daringfireball.net/projects/markdown/). Use the toolbar above, or click the **?** button for formatting help.
